set(ARCH ARM)

set(WOLFBOOT_TARGET xmc4700 CACHE INTERNAL "Target platform")

set(SIGN ED25519)
set(HASH SHA256)
set(VTOR 1)
set(SPMATH 1)
set(WOLFBOOT_PARTITION_SIZE 0x40000)
set(WOLFBOOT_SECTOR_SIZE 0x20000)
set(WOLFBOOT_PARTITION_BOOT_ADDRESS 0x0C040000)
set(WOLFBOOT_PARTITION_UPDATE_ADDRESS 0x0C080000)
set(WOLFBOOT_PARTITION_SWAP_ADDRESS 0x0C0C0000)

set(USER_HAL_SOURCES
  ${XMCLIB}/src/xmc4_flash.c
)
set(USER_HAL_INCLUDE_DIRS
  ${XMCLIB}/inc
  ${XMCLIB}/../CMSIS/Infineon/COMPONENT_XMC4700/Include
  ${PROJECT_SOURCE_DIR}/deps/firment/firmware/lib/CMSIS-6.1.0/Core/Include
)

set(KEYTOOLS_DIR ${PROJECT_BINARY_DIR}/../keytools)

set(BUILD_TEST_APPS no)
set(BUILD_IMAGE yes)